
title: Qianru Sun


#sidebar links
email: qianrusun AT smu DOT edu DOT sg
phone: 065-6826-1360
website: Google Scholar #do not add http://
linkedin: alandoe
github: sharu725
twitter: '@webjeda'
port: 4001
#Update all the sections by editing the files inside _includes folder.
